version: '3.8'

services:
  chroma-gradio-demo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - chroma_data:/app/chroma_db
      - ../data:/app/data:ro
    environment:
      - CHROMA_DB_PATH=/app/chroma_db
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - GRADIO_PORT=7860
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
    driver: local
